README.md

Signed-off-by: Richard Gee <richard@technologee.co.uk>

Add rgee0 progress and reformat

---

README.md

While I'm still waiting for my parts to arrive, here is my entry :)

Add technician Felix Pojtinger

---

README.md

Signed-off-by: Richard Gee richard@technologee.co.uk

Update rgee0 Gold link

---

README.md

Signed-off-by: Simon Emms simon@simonemms.com

Added Bronze and Silver levels for Simon Emms

---

README.md

Looks like I'm doing this thing!

Add martinwoodward

---

README.md

Update technicians table with link to my preview site.

Add martinwoodward preview site

---

README.md

Hi Alex, team, 
I'm pleased to join you in the game and fun of this growlab!

Add Philippe Ensarguet entry as lab technician

---

README.md

Signed-off-by: Simon Emms <simon@simonemms.com>

Add Gold and Platinum entries for MrSimonEmms

---

README.md

I'd like to take part in the contest.

Added myself to the list

---

README.md

Signed-off-by: Richard Gee richard@technologee.co.uk

Add number field to technicians table

---

README.md

Hi team,
I'm pleased to join the GrowLab journey !

Add Iboonox entry as lab technician

---

README.md

Signed-off-by: Richard Gee richard@technologee.co.uk

Add three new technicians

---

app/README.md
app/app.py
app/requirements.txt
app/sensors.py
app/specimen.py

This change supports no sensors and BMP280 in the live preview app
See the README for notes on how this works.

Support "no sensors" and BMP280 in the live preview app

---

README.md

add cpanato as Technicians

---

README.md

growlab/cpanato: add bronze and silver awards and add the live preview

---

app/README.md
app/growlab.service
app/sample.sh

Following the readme, some steps were missing and others need some adjustment.
This PR updates the steps and scripts to make it run from a fresh deployment.
/assing @alexellis

updates based on fresh start

---

README.md
app/README.md

Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>

Add country to lab technicians table

---

README.md

Hi Alex and team, I'd like to be added as a technician and have some fun with this growlab!

Add Marian to technicians list

---

README.md

https://twitter.com/SanderWaylay/status/1400716134094098433?s=20

Update README with gold badge for Sander

---

README.md

Add twitter links for Gold and Platinum level for Philippe Ensarguet

Add twitter links for Gold and Platinum level for Philippe Ensarguet

---

README.md

Add links to tweets for bronze, silver and gold levels for Marian

Add tweet links for Marian

---

README.md

Heyho!
I would love to join to this activity :)

add berlonics to Growlab technicians.

---

README.md

For the contests entries table, I update the twitter and youtube links.

update Antoine M. twitter links
